### PR TITLE
Release 2.0.0

### PR DESCRIPTION
**Pull request by biasso**
@tarunc Hi, there are a lot of changes in this pull request.
Decide if you want merge it or if it needs further changes.
You probably have to correct the documentation, my english isn't very good. :laughing:

**Changelog**:
* Rewrite all the code
* Improved documentation
* Improved tests
* Added a reporter (replaces the `showDiff` option)
* Added `debug` option
* Removed `mode` and `showDiff` options (use `gulp-diff` plugin instead)
* Changed logic of merging options
* Use 'snake_case' instead of 'camelCase' for options (for consistency with `js-beautify`)

### CODE REVIEW

**Comment by tarunc** [comment]
Hey @biasso, thanks for the major update-- I merged it in. Since I no longer use this module, I've been neglecting it for a long time. Do you want to get take over maintaining it? (Note that I already gave you push access to the repository-- since this is a major contribution/rewrite-- thanks again).

**Comment by tarunc** [comment]
@biasso What is your npmjs username?

**Comment by biasso** [comment]
Ok, I try to keep it updated.
Regarding npmjs I just created an account and my username is the same as github (biasso).

**Comment by tarunc** [comment]
@biasso I just gave you publish access on npm (see [npmjs/biasso](https://www.npmjs.com/~biasso)). You should be able to publish the package by going in the root directory of the project and running the command [`npm publish`](https://docs.npmjs.com/cli/publish). Let me know if you have any troubles.

**Pull request merged**
